version: '3.3'
services:
  monetizze-loteria:
    build: ./
    container_name: monetizze-loteria
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - docker
networks:
  docker:
    driver: bridge